version: '2'
networks:
    database:
        driver: bridge

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: passwd


  appserver:
    image: springio/spring-boot-boilerplate
    ports:
      - "8080:8080"